/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_TicTacToe;

/**
 *
 * @author Kyla Reambonanza
 */
public class start_window extends javax.swing.JFrame {

    /**
     * Creates new form start_window
     */
    public start_window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        one_player_butt = new javax.swing.JButton();
        two_player_butt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 199, 0));
        mainPanel.setMaximumSize(new java.awt.Dimension(1410, 680));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boardPanel.setBackground(new java.awt.Color(255, 255, 255));
        boardPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        boardPanel.setMaximumSize(new java.awt.Dimension(450, 450));
        boardPanel.setMinimumSize(new java.awt.Dimension(450, 450));
        boardPanel.setPreferredSize(new java.awt.Dimension(450, 450));
        boardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 199, 0));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        boardPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 470, 480));

        one_player_butt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main 1p.png"))); // NOI18N
        one_player_butt.setBorderPainted(false);
        one_player_butt.setContentAreaFilled(false);
        one_player_butt.setFocusPainted(false);
        one_player_butt.setMaximumSize(new java.awt.Dimension(200, 200));
        one_player_butt.setMinimumSize(new java.awt.Dimension(200, 200));
        one_player_butt.setPreferredSize(new java.awt.Dimension(200, 200));
        one_player_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_player_buttActionPerformed(evt);
            }
        });
        boardPanel.add(one_player_butt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 80));

        two_player_butt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main 2p.png"))); // NOI18N
        two_player_butt.setBorderPainted(false);
        two_player_butt.setContentAreaFilled(false);
        two_player_butt.setFocusPainted(false);
        two_player_butt.setMaximumSize(new java.awt.Dimension(200, 200));
        two_player_butt.setMinimumSize(new java.awt.Dimension(200, 200));
        two_player_butt.setPreferredSize(new java.awt.Dimension(200, 200));
        two_player_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_player_buttActionPerformed(evt);
            }
        });
        boardPanel.add(two_player_butt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 240, 80));

        mainPanel.add(boardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 470, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 480, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void one_player_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_player_buttActionPerformed
        Java_TicTacToe open_game_window = new Java_TicTacToe();
        open_game_window.show();  // display Java_TicTacToe here
        
        dispose(); // close current frame (start_window) after opening Java_TicTacToe
    }//GEN-LAST:event_one_player_buttActionPerformed

    private void two_player_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_player_buttActionPerformed
        Java_TicTacToe open_game_window = new Java_TicTacToe();
        open_game_window.show();  // display Java_TicTacToe here
        
        dispose(); // close current frame (start_window) after opening Java_TicTacToe
    }//GEN-LAST:event_two_player_buttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton one_player_butt;
    private javax.swing.JButton two_player_butt;
    // End of variables declaration//GEN-END:variables
}
